name: Docker Publish

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*' ]

env:
  # Use docker.io for Docker Hub if empty
  IMAGE_NAME: harip220/gitops-hello-demo   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set tag environment variable
      run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV 

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Build and push Docker image
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: harip220/gitops-hello-demo:${{ env.TAG_NAME }}               